### ISSUE TITLE
Show SQ graph when Staircase view enabled

### ISSUE THREAD

**Issue by agwblack** [dsjoerg/ggtracker#18]
I think a nice feature would be to have a graph that shows Spending Quotient against match number, when Staircase View is enabled. This would let users easily see their progress over time (at the moment you have to mouse over the Spending Skill medal).

**Comment by dsjoerg** [comment]
One the one hand this would be cool, on the other hand I think you would find it frustrating because SQ is systematically higher for shorter games.  (See http://ggtracker.com/spending_skill_stats#?race=protoss&gateway=am)   So there would be a fair amount of noise in the SQ graph that's unrelated to the actual spending skill of the player.

That said, as long as it's done in a way that doesn't confuse or overwhelm the users I'm all for it, and it would be fun to see something new on the site after ~2 years of the same old same old :)

**Comment by agwblack** [comment]
So Spending Skill is just the SQ adjusted for game length? How does this work precisely?

**Comment by dsjoerg** [comment]
See http://ggtracker.com/spending_skill

**Comment by dsjoerg** [comment]
This issue was moved to ggtracker/ggtrackerstack#27
